name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/training-api:${{ env.TAG_NAME }} --platform=linux/amd64,linux/arm64 .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/training-api:${{ env.TAG_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/training-api:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/training-api:${{ env.TAG_NAME }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/training-api:latest
